[settings]
experimental = true

[tools]
java = "25"
node = "22"
npm = "latest"
"npm:@earendil-works/pi-coding-agent" = "0.85.1"

[tasks.pi]
description = "Run Pi"
tools.node = "22"
dir = "{{cwd}}"
raw = true
raw_args = true
quiet = true
run = "exec pi"
